#!/usr/bin/env bash
# =============================================================================
# LiteSOC Agent — One-Line Installer
# =============================================================================
# Usage:
#   curl -sSL https://litesoc.io/install.sh | \
#     LITESOC_KEY=lsoc_live_xxx \
#     bash
#
# The script will:
#   1. Detect OS / architecture.
#   2. Download the pre-built binary from GitHub Releases.
#   3. Write /etc/litesoc/config.yaml (skipped if already present).
#   4. Store the agent key in /etc/litesoc/agent.env (chmod 600).
#   5. Install and start a systemd service (if systemd is available).
# =============================================================================
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
REPO="litesoc/litesoc-agent"
BINARY_NAME="litesoc-agent"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/litesoc"
SERVICE_NAME="litesoc-agent"
VERSION="${LITESOC_AGENT_VERSION:-latest}"

# ── Validate required env vars ────────────────────────────────────────────────
if [[ -z "${LITESOC_KEY:-}" ]]; then
  echo "ERROR: LITESOC_KEY is not set." >&2
  echo "       Export it before running:" >&2
  echo "         export LITESOC_KEY=lsoc_live_your_key" >&2
  exit 1
fi

# ── Detect OS and architecture ────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
RAW_ARCH="$(uname -m)"

case "${RAW_ARCH}" in
  x86_64)          ARCH="amd64" ;;
  aarch64 | arm64) ARCH="arm64" ;;
  armv7l)          ARCH="arm"   ;;
  *)
    echo "ERROR: Unsupported architecture: ${RAW_ARCH}" >&2
    exit 1
    ;;
esac

if [[ "${OS}" != "linux" && "${OS}" != "darwin" ]]; then
  echo "ERROR: Unsupported operating system: ${OS}" >&2
  exit 1
fi

echo "==> LiteSOC Agent Installer"
echo "    Platform : ${OS}/${ARCH}"
echo "    Version  : ${VERSION}"
echo ""

# ── Resolve download URL ──────────────────────────────────────────────────────
if [[ "${VERSION}" == "latest" ]]; then
  RELEASE_PATH="latest/download"
else
  RELEASE_PATH="download/${VERSION}"
fi

ARCHIVE="${BINARY_NAME}_${OS}_${ARCH}.tar.gz"
DOWNLOAD_URL="https://github.com/${REPO}/releases/${RELEASE_PATH}/${ARCHIVE}"

# ── Download and install binary ───────────────────────────────────────────────
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

echo "==> Downloading ${DOWNLOAD_URL} ..."
curl -sSL --fail "${DOWNLOAD_URL}" -o "${TMP_DIR}/${ARCHIVE}"

echo "==> Extracting ..."
tar -xzf "${TMP_DIR}/${ARCHIVE}" -C "${TMP_DIR}"

echo "==> Installing binary to ${INSTALL_DIR}/${BINARY_NAME} ..."
sudo install -m 0755 "${TMP_DIR}/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"

# ── Create config directory ───────────────────────────────────────────────────
sudo mkdir -p "${CONFIG_DIR}"

# ── Write default config.yaml (idempotent) ────────────────────────────────────
if [[ ! -f "${CONFIG_DIR}/config.yaml" ]]; then
  echo "==> Writing default config to ${CONFIG_DIR}/config.yaml ..."
  sudo tee "${CONFIG_DIR}/config.yaml" > /dev/null <<YAML
# LiteSOC Agent Configuration — generated by installer
api_endpoint: https://api.litesoc.io
heartbeat_interval: 60

log_watchers:
  - path: /var/log/auth.log
    type: sshd
  # Fedora / RHEL / CentOS:
  # - path: /var/log/secure
  #   type: sshd
YAML
else
  echo "==> Config already exists at ${CONFIG_DIR}/config.yaml — skipping."
fi

# ── Store agent key securely (chmod 600, root-only) ───────────────────────────
echo "==> Writing agent key to ${CONFIG_DIR}/agent.env ..."
sudo tee "${CONFIG_DIR}/agent.env" > /dev/null <<ENV
LITESOC_KEY=${LITESOC_KEY}
ENV
sudo chmod 600 "${CONFIG_DIR}/agent.env"
sudo chown root:root "${CONFIG_DIR}/agent.env"

# ── Install systemd service (Linux only) ──────────────────────────────────────
if [[ "${OS}" == "linux" ]] && command -v systemctl &>/dev/null; then
  echo "==> Installing systemd service: ${SERVICE_NAME}.service ..."
  sudo tee "/etc/systemd/system/${SERVICE_NAME}.service" > /dev/null <<UNIT
[Unit]
Description=LiteSOC Security Agent
Documentation=https://litesoc.io/docs/integrations/agent
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
User=root
EnvironmentFile=${CONFIG_DIR}/agent.env
ExecStart=${INSTALL_DIR}/${BINARY_NAME} ${CONFIG_DIR}/config.yaml
Restart=on-failure
RestartSec=10

# Resource guardrails — keeps the agent well within the <20 MB / <1% CPU targets.
MemoryMax=32M
CPUQuota=5%

# Harden the service's access to the host.
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/var/log

[Install]
WantedBy=multi-user.target
UNIT

  sudo systemctl daemon-reload
  sudo systemctl enable --now "${SERVICE_NAME}"

  echo ""
  echo "✓ LiteSOC Agent installed and started."
  echo "  Status  : systemctl status ${SERVICE_NAME}"
  echo "  Logs    : journalctl -u ${SERVICE_NAME} -f"
  echo "  Config  : ${CONFIG_DIR}/config.yaml"

else
  # macOS / no-systemd fallback: print manual run instructions.
  echo ""
  echo "✓ LiteSOC Agent installed to ${INSTALL_DIR}/${BINARY_NAME}"
  echo ""
  echo "  Run manually:"
  echo "    source ${CONFIG_DIR}/agent.env && \\"
  echo "    ${INSTALL_DIR}/${BINARY_NAME} ${CONFIG_DIR}/config.yaml"
  echo ""
  echo "  For a launchd plist (macOS), see:"
  echo "    https://litesoc.io/docs/integrations/agent#service-mgmt"
fi
